on: [push, pull_request]

name: CI

jobs:
  build:
    name: Build project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fastlane
        run: bundle install
      - name: Build
        run: bundle exec fastlane build
